version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"  # Application Entry
      - "8421:8421"  # Remote Debugging
    volumes:
      - ./core:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             daphne core.asgi:application -b 0.0.0.0 -p 8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=shittypassword  
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
  db:
    image: postgres:12.13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shittypassword
    ports:
      - "5432:5432"
    volumes:
       - data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.7-bullseye
    ports:
      - "6379:6379"

volumes:
  data:
